#30: Build versioned package

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,7 +1,7 @@
 # This workflow will install Python dependencies, run tests and lint with a variety of Python versions
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
 
-name: Python package
+name: Release
 
 on:
   release:
@@ -168,7 +168,24 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: "Trigger docs deployment"
+      - name: Sync Readthedocs versions
+        env:
+          READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
+        run: |
+          curl --fail -X POST -H "Authorization: Token ${READTHEDOCS_TOKEN}" https://readthedocs.org/api/v3/projects/domprob/sync-versions/ || exit 1
+
+      - name: "Activate new version '${{ github.event.release.tag_name }}'"
+        env:
+          READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
+          VERSION: "${{ github.event.release.tag_name }}"
+        run: |
+          curl --fail -X PATCH \
+            -H "Authorization: Token ${READTHEDOCS_TOKEN}" \
+            -H "Content-Type: application/json" \
+            -d '{"active": true}' \
+            https://readthedocs.org/api/v3/projects/domprob/versions/${VERSION}/ || exit 1
+
+      - name: "Trigger docs deployment '${{ github.event.release.tag_name }}'"
         env:
           READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
           VERSION: ${{ github.event.release.tag_name }}
@@ -190,13 +207,13 @@ jobs:
 
             echo "Polling deployment state... $build_state"
 
-            if [ "$build_state" == "finished" ]; then
+            if [[ "$build_state" == "finished" ]]; then
               echo "Deployment success: $build_success"
-              if [ "$build_success" == "true" ]; then
-                echo "Read the Docs build completed successfully."
+              if [[ "$build_success" == "true" ]]; then
+                echo "✅ Read the Docs build completed successfully."
                 break
               else:
-                echo "Read the Docs build failed."
+                echo "❌ Read the Docs build failed."
                 exit 1
               fi
             fi
